In [2]:
import numpy as np
import re

In [47]:
data_dir = r'\\storage01.amolf.nl\data\AMOLF\users\singh\Lisa PSO Runs\Order Parameter Study\100000 Runs\Data'
cog_social = [[0,14], [0,13], [0,12], [0,11], [0,10], [0,9], [0,8], [0,7],
              [1,13], [1,12], [1,11], [1,10], [1,9], [1,8], [1,7],
              [2,12], [2,11], [2,10], [2,9], [2,8], [2,7],
              [3,11], [3,10], [3,9], [3,8], [3,7],
              [4,10], [4,9], [4,8], [4,7],
              [5,9], [5,8], [5,7],
              [6,8], [6,7],
              [7,7]]

file_each = 3000
order_param_r2 = np.ones((36*file_each, 8, 8))*np.nan

Position  = np.zeros((12, 2))
Positions = np.zeros((108000, 12, 2))

remaining = 36*file_each
i = 0
for cf, sf in cog_social:
        print(i)
        for filecount in range(0, file_each):
            str1 = "%02d"%(cf*25+0)
            str2 = "%02d"%(sf*25+0)
            str3 = "%02d"%(filecount)    
            fp = open(data_dir+ '\RunPso_c' + str1 +'_s'+ str2 +'_r'+ str3)
            
            for j, line in enumerate(fp):
                  if(j >= 3415 and j<= 3426):
                    test = re.split(r'\t+', line)
                    Position[j-3415,0] = float(test[0])
                    Position[j-3415,1] = float(test[1])
            i = i + 1        
            Positions[i] = Position / 4

0
3000
6000
9000
12000
15000
18000
21000
24000
27000
30000
33000
36000
39000
42000
45000
48000
51000
54000
57000
60000
63000
66000
69000
72000
75000
78000
81000
84000
87000
90000
93000
96000
99000
102000
105000


IndexError: index 108000 is out of bounds for axis 0 with size 108000

In [48]:
import scipy.io
scipy.io.savemat(r'\\storage01.amolf.nl\data\AMOLF\users\singh\Nitin\Sammon Mapping\Positions_108000.mat', {'Positions': Positions[0:105000]})

In [49]:
mapped_position = scipy.io.loadmat(r'C:\Users\singh\Desktop\Mapped_Positions.mat')

In [21]:
from matplotlib import pyplot as plt
for count in range(54000):
    x = mapped_position['y_stacked'][count,0]; y = mapped_position['y_stacked'][count,1]
    plt.plot(x,y, 'o', markersize = 1)
plt.show()

In [59]:
plt.plot(mapped_position['y_stacked'][:,0], mapped_position['y_stacked'][:,1], 'o', markersize =1, markeredgecolor = 'None', alpha = 0.50)
#plt.xlim(-2,2)
#plt.ylim(-2,2)
plt.show()

In [60]:
fitness_array = np.load(r"\\storage01.amolf.nl\data\AMOLF\users\singh\Lisa PSO Runs\Order Parameter Study\100000 Runs\Data\Data\best_cost_grid.npy")

In [91]:
fitness_array_for_mapping_colormap = np.zeros((105000,1))

In [137]:
for i in range(8):
    fitness_array_for_mapping_colormap[3000*i:3000*(i+1),0] = fitness_array[:,7-i,0]

In [138]:
for i in range(7):
    fitness_array_for_mapping_colormap[24000+3000*i:24000+3000*(i+1),0] = fitness_array[:,6-i,1]

In [139]:
for i in range(6):
    fitness_array_for_mapping_colormap[45000+3000*i:45000+3000*(i+1),0] = fitness_array[:,5-i,2]

In [140]:
for i in range(5):
    fitness_array_for_mapping_colormap[63000+3000*i:63000+3000*(i+1),0] = fitness_array[:,4-i,3]

In [141]:
for i in range(4):
    fitness_array_for_mapping_colormap[78000+3000*i:78000+3000*(i+1),0] = fitness_array[:,3-i,4]

In [142]:
for i in range(3):
    fitness_array_for_mapping_colormap[90000+3000*i:90000+3000*(i+1),0] = fitness_array[:,2-i,5]

In [143]:
for i in range(2):
    fitness_array_for_mapping_colormap[99000+3000*i:99000+3000*(i+1),0] = fitness_array[:,1-i,6]

array([ 0.00012801])

In [107]:
fitness_array_for_mapping_colormap.max()

0.04067879531572928

In [106]:
fitness_array_for_mapping_colormap.min()

3.3886906797320248e-11

In [159]:
import colormaps as cmaps
#plt.register_cmap(name='viridis', cmap=cmaps.viridis)
#from mattplotlib import colors
cmap = plt.get_cmap('jet_r')
#cmap = cmaps.plasma
import matplotlib as mpl
norm = mpl.colors.LogNorm(vmax=0.0406, vmin=1e-5)

for i in range(105000):
         clr = cmap(norm(fitness_array_for_mapping_colormap[i,0]))
         plt.plot(mapped_position['y_stacked'][i,0], mapped_position['y_stacked'][i,1], 'o'
         , color = clr, markersize =1, markeredgecolor = clr)
plt.show()

In [113]:
fitness_array_for_mapping_colormap[0:100,0]

array([  2.11789566e-04,   8.13316740e-05,   3.29753628e-04,
         7.95148350e-05,   1.30843136e-04,   3.18233139e-04,
         7.13101173e-05,   4.37853927e-04,   8.20477732e-05,
         5.43127552e-04,   8.32905809e-05,   6.63967639e-04,
         1.21490017e-04,   4.57408094e-05,   3.20170657e-03,
         1.45392723e-04,   2.38881835e-04,   3.25537490e-04,
         1.00265679e-04,   7.23712708e-05,   1.15436108e-04,
         2.85180491e-04,   3.35588250e-04,   1.78850368e-04,
         1.75536235e-04,   6.77134626e-04,   1.63228970e-04,
         2.09390947e-05,   9.10824430e-03,   9.00704519e-05,
         4.25726274e-05,   4.82575026e-04,   1.04084762e-04,
         5.70468401e-04,   5.24666147e-04,   1.29425781e-05,
         9.26097803e-05,   9.51650448e-05,   3.82452575e-04,
         4.31775835e-05,   9.50693231e-05,   6.36856402e-05,
         1.64993815e-04,   6.57147693e-05,   1.38574490e-04,
         2.16822275e-04,   1.96253210e-04,   8.54881898e-05,
         1.74040144e-04,

In [136]:
Positions[105000-1]

array([[-0.95860599,  0.8294437 ],
       [-0.31699929,  1.3542717 ],
       [ 0.53221478,  0.95317249],
       [ 1.34642378,  0.99657069],
       [ 0.98538235, -0.38074304],
       [ 0.95310183, -1.38308076],
       [-1.54627555, -1.38942996],
       [-1.57083884, -0.21708284],
       [-0.17641784, -0.20158462],
       [ 0.35374447,  0.48596876],
       [ 0.54449478, -0.14484534],
       [ 0.62348833, -0.95002267]])